#!/usr/bin/env python3
"""Injects/refreshes canonical, Open Graph, Twitter Card, favicon, and
JSON-LD structured-data tags into every page's <head>, driven by
articles/manifest.json for article-specific data.

Idempotent: looks for an <!-- SEO:START --> ... <!-- SEO:END --> block and
replaces it if present, otherwise inserts one right after the
<meta name="description"> tag. Safe to re-run any time (e.g. after the
daily content engine adds a new article) — run gen_sitemap.py and
gen_og_images.py first so this can reference the new files.
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # site/
BASE_URL = "https://oddslighthouse.com"
SITE_NAME = "OddsLighthouse"
DEFAULT_OG = "/assets/og/site-default.png"

with open(os.path.join(ROOT, "articles", "manifest.json")) as f:
    MANIFEST = {a["slug"]: a for a in json.load(f)["articles"]}

# path (relative to site/) -> (title_override_or_None, breadcrumb list of (name, url_or_None))
STATIC_PAGES = {
    "index.html": [("Home", None)],
    "betting.html": [("Home", "/"), ("Sports Betting", None)],
    "casino.html": [("Home", "/"), ("Casino", None)],
    "responsible-gambling.html": [("Home", "/"), ("Responsible Gambling", None)],
    "about.html": [("Home", "/"), ("About", None)],
    "disclosure.html": [("Home", "/"), ("Advertising Disclosure", None)],
    "privacy.html": [("Home", "/"), ("Privacy Policy", None)],
    "articles/index.html": [("Home", "/"), ("All Guides", None)],
}

def get_tag_content(html, tag_pattern):
    m = re.search(tag_pattern, html, re.S)
    return m.group(1).strip() if m else ""

def esc(s):
    return s.replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")

def build_breadcrumb_jsonld(crumbs):
    items = []
    for i, (name, url) in enumerate(crumbs, start=1):
        entry = {"@type": "ListItem", "position": i, "name": name}
        if url is not None:
            entry["item"] = BASE_URL + url
        items.append(entry)
    return {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": items}

def build_head_block(rel_path, html):
    is_article = rel_path.startswith("articles/") and rel_path not in ("articles/index.html",)
    depth = rel_path.count("/")
    prefix = "../" * depth

    title = get_tag_content(html, r"<title>(.*?)</title>")
    description = get_tag_content(html, r'<meta name="description" content="(.*?)">')
    url_path = "/" + rel_path.replace("index.html", "") if rel_path != "index.html" else "/"
    canonical = BASE_URL + url_path

    ld_blocks = []

    if is_article:
        slug = rel_path.split("/")[-1].replace(".html", "")
        art = MANIFEST.get(slug, {})
        og_image = f"/assets/og/{slug}.png"
        og_type = "article"
        crumbs = [("Home", "/"), ("Sports Betting" if art.get("category") != "Casino Guides" else "Casino",
                   "/betting.html" if art.get("category") != "Casino Guides" else "/casino.html"),
                  (art.get("title", title), None)]
        ld_blocks.append({
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": art.get("title", title),
            "description": art.get("excerpt", description),
            "image": BASE_URL + og_image,
            "datePublished": art.get("date", ""),
            "dateModified": art.get("date", ""),
            "author": {"@type": "Organization", "name": SITE_NAME, "url": BASE_URL},
            "publisher": {
                "@type": "Organization", "name": SITE_NAME,
                "logo": {"@type": "ImageObject", "url": BASE_URL + "/assets/apple-touch-icon.png"}
            },
            "mainEntityOfPage": {"@type": "WebPage", "@id": canonical}
        })
    else:
        og_image = DEFAULT_OG
        og_type = "website"
        crumbs = STATIC_PAGES.get(rel_path, [("Home", None)])
        if rel_path == "index.html":
            ld_blocks.append({
                "@context": "https://schema.org",
                "@type": "Organization",
                "name": SITE_NAME,
                "url": BASE_URL + "/",
                "logo": BASE_URL + "/assets/apple-touch-icon.png"
            })
            ld_blocks.append({
                "@context": "https://schema.org",
                "@type": "WebSite",
                "name": SITE_NAME,
                "url": BASE_URL + "/"
            })

    if len(crumbs) > 1:
        ld_blocks.append(build_breadcrumb_jsonld(crumbs))

    og_image_abs = BASE_URL + og_image

    lines = []
    lines.append('<!-- SEO:START (generated by assets/inject_seo_head.py — do not hand-edit, re-run script) -->')
    lines.append(f'<link rel="canonical" href="{canonical}">')
    lines.append(f'<link rel="icon" type="image/svg+xml" href="{prefix}assets/favicon.svg">')
    lines.append(f'<link rel="icon" type="image/png" sizes="32x32" href="{prefix}assets/favicon-32.png">')
    lines.append(f'<link rel="apple-touch-icon" sizes="180x180" href="{prefix}assets/apple-touch-icon.png">')
    lines.append('<meta name="theme-color" content="#16233d">')
    lines.append(f'<meta property="og:site_name" content="{SITE_NAME}">')
    lines.append(f'<meta property="og:type" content="{og_type}">')
    lines.append(f'<meta property="og:title" content="{esc(title)}">')
    lines.append(f'<meta property="og:description" content="{esc(description)}">')
    lines.append(f'<meta property="og:url" content="{canonical}">')
    lines.append(f'<meta property="og:image" content="{og_image_abs}">')
    lines.append('<meta property="og:image:width" content="1200">')
    lines.append('<meta property="og:image:height" content="630">')
    lines.append('<meta property="og:locale" content="en_US">')
    lines.append('<meta name="twitter:card" content="summary_large_image">')
    lines.append(f'<meta name="twitter:title" content="{esc(title)}">')
    lines.append(f'<meta name="twitter:description" content="{esc(description)}">')
    lines.append(f'<meta name="twitter:image" content="{og_image_abs}">')
    for block in ld_blocks:
        lines.append('<script type="application/ld+json">' + json.dumps(block, ensure_ascii=False) + '</script>')
    lines.append('<!-- SEO:END -->')
    return "\n".join(lines)

def process_file(path, rel_path):
    with open(path) as f:
        html = f.read()
    block = build_head_block(rel_path, html)

    if "<!-- SEO:START" in html:
        html = re.sub(r"<!-- SEO:START.*?<!-- SEO:END -->", block, html, flags=re.S)
    else:
        # insert right after the meta description tag
        marker = re.search(r'<meta name="description" content=".*?">\n', html)
        if not marker:
            print(f"  SKIP (no description tag found): {rel_path}")
            return
        idx = marker.end()
        html = html[:idx] + block + "\n" + html[idx:]

    with open(path, "w") as f:
        f.write(html)
    print(f"  updated {rel_path}")

def main():
    for rel_path in list(STATIC_PAGES.keys()):
        process_file(os.path.join(ROOT, rel_path), rel_path)
    art_dir = os.path.join(ROOT, "articles")
    for fname in sorted(os.listdir(art_dir)):
        if fname.endswith(".html") and fname != "index.html":
            rel_path = f"articles/{fname}"
            process_file(os.path.join(ROOT, rel_path), rel_path)

if __name__ == "__main__":
    main()
